### ISSUE TITLE
Instant crash on startup

### ISSUE THREAD

**Issue by heroin-moose** [russelltg/wl-screenrec#27]
Running wl-screenrec results in instant crash.

Compositor:
```
$ labwc 0.6.4-57-gbd6efe4-dirty (wlroots 0.16.2)
```

Stack trace:
```
$ RUST_BACKTRACE=full cargo run --quiet 2>&1 | wl-copy
thread 'main' panicked at 'Missing event_created_child specialization for event opcode 1 of wp_drm_lease_device_v1', /home/consus/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.30.2/src/event_queue.rs:124:9
stack backtrace:
   0:     0x55b439adf7a1 - std::backtrace_rs::backtrace::libunwind::trace::h6aeaf83abc038fe6
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55b439adf7a1 - std::backtrace_rs::backtrace::trace_unsynchronized::h4f9875212db0ad97
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b439adf7a1 - std::sys_common::backtrace::_print_fmt::h3f820027e9c39d3b
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55b439adf7a1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hded4932df41373b3
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55b439b01d9f - core::fmt::rt::Argument::fmt::hc8ead7746b2406d6
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/fmt/rt.rs:138:9
   5:     0x55b439b01d9f - core::fmt::write::hb1cb56105a082ad9
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/fmt/mod.rs:1094:21
   6:     0x55b439add431 - std::io::Write::write_fmt::h797fda7085c97e57
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/io/mod.rs:1713:15
   7:     0x55b439adf5b5 - std::sys_common::backtrace::_print::h492d3c92d7400346
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55b439adf5b5 - std::sys_common::backtrace::print::hf74aa2eef05af215
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55b439ae0a57 - std::panicking::default_hook::{{closure}}::h8cad394227ea3de8
  10:     0x55b439ae0844 - std::panicking::default_hook::h249cc184fec99a8a
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:288:9
  11:     0x55b439ae0f0c - std::panicking::rust_panic_with_hook::h82ebcd5d5ed2fad4
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:705:13
  12:     0x55b439ae0e07 - std::panicking::begin_panic_handler::{{closure}}::h810bed8ecbe66f1a
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:597:13
  13:     0x55b439adfbd6 - std::sys_common::backtrace::__rust_end_short_backtrace::h1410008071796261
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55b439ae0b52 - rust_begin_unwind
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
  15:     0x55b4398746a3 - core::panicking::panic_fmt::ha0a42a25e0cf258d
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
  16:     0x55b4398d4188 - wayland_client::event_queue::Dispatch::event_created_child::hf2924369910c3581
                               at /home/consus/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.30.2/src/event_queue.rs:124:9
  17:     0x55b4398f4630 - <wayland_client::event_queue::QueueProxyData<I,U,State> as wayland_backend::rs::client::ObjectData>::event::{{closure}}::h750ca9520c426875
                               at /home/consus/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.30.2/src/event_queue.rs:676:22
  18:     0x55b4398a08da - core::bool::<impl bool>::then::h0075495a04b6b715
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/bool.rs:60:24
  19:     0x55b4398f1817 - <wayland_client::event_queue::QueueProxyData<I,U,State> as wayland_backend::rs::client::ObjectData>::event::h2a12d49de90f9adb
                               at /home/consus/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.30.2/src/event_queue.rs:672:24
  20:     0x55b439941f29 - wayland_backend::rs::client_impl::dispatch_events::he6d3a8f0d31a36fe
                               at /home/consus/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.1.2/src/rs/client_impl/mod.rs:773:19
  21:     0x55b43993babb - wayland_backend::rs::client_impl::InnerReadEventsGuard::read::h39e164f9820c302f
                               at /home/consus/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.1.2/src/rs/client_impl/mod.rs:235:23
  22:     0x55b43992aada - wayland_backend::rs::client::ReadEventsGuard::read::had955d77da01477e
                               at /home/consus/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.1.2/src/rs/../client_api.rs:323:9
  23:     0x55b43992fc60 - wayland_client::conn::blocking_read::h5a812b2f73d47503
                               at /home/consus/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.30.2/src/conn.rs:239:11
  24:     0x55b4398f7d21 - wayland_client::event_queue::EventQueue<State>::blocking_dispatch::hdcc3956185bf5db6
                               at /home/consus/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.30.2/src/event_queue.rs:399:13
  25:     0x55b439890307 - wl_screenrec::main::hfd38f2488fb34122
                               at /home/consus/src/wl-screenrec/src/main.rs:1646:9
  26:     0x55b4398e35cb - core::ops::function::FnOnce::call_once::h0b77117dfabe3197
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
  27:     0x55b4398caf7e - std::sys_common::backtrace::__rust_begin_short_backtrace::hc58586225284c2d8
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:135:18
  28:     0x55b4398dad71 - std::rt::lang_start::{{closure}}::hbcfb689997a4e9b2
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:166:18
  29:     0x55b439ad8875 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h5ce27e764c284c0a
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:284:13
  30:     0x55b439ad8875 - std::panicking::try::do_call::h4c1fc390ae241991
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
  31:     0x55b439ad8875 - std::panicking::try::h4d36e7eaed86af72
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
  32:     0x55b439ad8875 - std::panic::catch_unwind::h41cfb4dd65282b1e
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
  33:     0x55b439ad8875 - std::rt::lang_start_internal::{{closure}}::hfed411c1c5fdb925
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:148:48
  34:     0x55b439ad8875 - std::panicking::try::do_call::h6893f6f32a464342
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
  35:     0x55b439ad8875 - std::panicking::try::h52b7102f469a0567
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
  36:     0x55b439ad8875 - std::panic::catch_unwind::h62120054677916b5
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
  37:     0x55b439ad8875 - std::rt::lang_start_internal::hd66bf6b7da144005
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:148:20
  38:     0x55b4398dad4a - std::rt::lang_start::h9f25c2efd8812171
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:165:17
  39:     0x55b439895c2e - main
  40:     0x7fc4df427cd0 - <unknown>
  41:     0x7fc4df427d8a - __libc_start_main
  42:     0x55b439874ed5 - _start
  43:                0x0 - <unknown>
```

wayland-info:
```
$ wayland-info
interface: 'wl_shm',                                     version:  1, name:  1
	formats (fourcc):
	0x38344241 = 'AB48'
	0x38344258 = 'XB48'
	0x48344241 = 'AB4H'
	0x48344258 = 'XB4H'
	0x30334241 = 'AB30'
	0x30334258 = 'XB30'
	0x36314752 = 'RG16'
	0x35314152 = 'RA15'
	0x35315852 = 'RX15'
	0x32314152 = 'RA12'
	0x32315852 = 'RX12'
	0x34324742 = 'BG24'
	0x34324241 = 'AB24'
	0x34324258 = 'XB24'
	         1 = 'XR24'
	         0 = 'AR24'
interface: 'wl_drm',                                     version:  2, name:  2
interface: 'zwp_linux_dmabuf_v1',                        version:  4, name:  3
	main device: 0xE280 (/dev/dri/card1 or /dev/dri/renderD128)
	tranche
		target device: 0xE280 (/dev/dri/card1 or /dev/dri/renderD128)
		flags: none
		formats (fourcc) and modifiers (names):
		0x48344241 = 'AB4H'; 0x00ffffffffffffff = INVALID
		0x48344241 = 'AB4H'; 0x0000000000000000 = LINEAR
		0x48344241 = 'AB4H'; 0x0100000000000001 = INTEL_X_TILED
		0x48344241 = 'AB4H'; 0x0100000000000002 = INTEL_Y_TILED
		0x48344241 = 'AB4H'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x48344241 = 'AB4H'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x48344258 = 'XB4H'; 0x00ffffffffffffff = INVALID
		0x48344258 = 'XB4H'; 0x0000000000000000 = LINEAR
		0x48344258 = 'XB4H'; 0x0100000000000001 = INTEL_X_TILED
		0x48344258 = 'XB4H'; 0x0100000000000002 = INTEL_Y_TILED
		0x48344258 = 'XB4H'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x48344258 = 'XB4H'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x38344241 = 'AB48'; 0x00ffffffffffffff = INVALID
		0x38344241 = 'AB48'; 0x0000000000000000 = LINEAR
		0x38344241 = 'AB48'; 0x0100000000000001 = INTEL_X_TILED
		0x38344241 = 'AB48'; 0x0100000000000002 = INTEL_Y_TILED
		0x38344241 = 'AB48'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x38344241 = 'AB48'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x38344258 = 'XB48'; 0x00ffffffffffffff = INVALID
		0x38344258 = 'XB48'; 0x0000000000000000 = LINEAR
		0x38344258 = 'XB48'; 0x0100000000000001 = INTEL_X_TILED
		0x38344258 = 'XB48'; 0x0100000000000002 = INTEL_Y_TILED
		0x38344258 = 'XB48'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x38344258 = 'XB48'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x30335241 = 'AR30'; 0x00ffffffffffffff = INVALID
		0x30335241 = 'AR30'; 0x0000000000000000 = LINEAR
		0x30335241 = 'AR30'; 0x0100000000000001 = INTEL_X_TILED
		0x30335241 = 'AR30'; 0x0100000000000002 = INTEL_Y_TILED
		0x30335241 = 'AR30'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x30335241 = 'AR30'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x30335258 = 'XR30'; 0x00ffffffffffffff = INVALID
		0x30335258 = 'XR30'; 0x0000000000000000 = LINEAR
		0x30335258 = 'XR30'; 0x0100000000000001 = INTEL_X_TILED
		0x30335258 = 'XR30'; 0x0100000000000002 = INTEL_Y_TILED
		0x30335258 = 'XR30'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x30335258 = 'XR30'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x30334241 = 'AB30'; 0x00ffffffffffffff = INVALID
		0x30334241 = 'AB30'; 0x0000000000000000 = LINEAR
		0x30334241 = 'AB30'; 0x0100000000000001 = INTEL_X_TILED
		0x30334241 = 'AB30'; 0x0100000000000002 = INTEL_Y_TILED
		0x30334241 = 'AB30'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x30334241 = 'AB30'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x34325241 = 'AR24'; 0x00ffffffffffffff = INVALID
		0x34325241 = 'AR24'; 0x0000000000000000 = LINEAR
		0x34325241 = 'AR24'; 0x0100000000000001 = INTEL_X_TILED
		0x34325241 = 'AR24'; 0x0100000000000002 = INTEL_Y_TILED
		0x34325241 = 'AR24'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x34325241 = 'AR24'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x34325241 = 'AR24'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x34324241 = 'AB24'; 0x00ffffffffffffff = INVALID
		0x34324241 = 'AB24'; 0x0000000000000000 = LINEAR
		0x34324241 = 'AB24'; 0x0100000000000001 = INTEL_X_TILED
		0x34324241 = 'AB24'; 0x0100000000000002 = INTEL_Y_TILED
		0x34324241 = 'AB24'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x34324241 = 'AB24'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x34324241 = 'AB24'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x34325258 = 'XR24'; 0x00ffffffffffffff = INVALID
		0x34325258 = 'XR24'; 0x0000000000000000 = LINEAR
		0x34325258 = 'XR24'; 0x0100000000000001 = INTEL_X_TILED
		0x34325258 = 'XR24'; 0x0100000000000002 = INTEL_Y_TILED
		0x34325258 = 'XR24'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x34325258 = 'XR24'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x34325258 = 'XR24'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x34324258 = 'XB24'; 0x00ffffffffffffff = INVALID
		0x34324258 = 'XB24'; 0x0000000000000000 = LINEAR
		0x34324258 = 'XB24'; 0x0100000000000001 = INTEL_X_TILED
		0x34324258 = 'XB24'; 0x0100000000000002 = INTEL_Y_TILED
		0x34324258 = 'XB24'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x34324258 = 'XB24'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x34324258 = 'XB24'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x35315241 = 'AR15'; 0x00ffffffffffffff = INVALID
		0x35315241 = 'AR15'; 0x0000000000000000 = LINEAR
		0x35315241 = 'AR15'; 0x0100000000000001 = INTEL_X_TILED
		0x35315241 = 'AR15'; 0x0100000000000002 = INTEL_Y_TILED
		0x35315241 = 'AR15'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x35315241 = 'AR15'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x36314752 = 'RG16'; 0x00ffffffffffffff = INVALID
		0x36314752 = 'RG16'; 0x0000000000000000 = LINEAR
		0x36314752 = 'RG16'; 0x0100000000000001 = INTEL_X_TILED
		0x36314752 = 'RG16'; 0x0100000000000002 = INTEL_Y_TILED
		0x36314752 = 'RG16'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x36314752 = 'RG16'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x20203852 = 'R8  '; 0x00ffffffffffffff = INVALID
		0x20203852 = 'R8  '; 0x0000000000000000 = LINEAR
		0x20203852 = 'R8  '; 0x0100000000000001 = INTEL_X_TILED
		0x20203852 = 'R8  '; 0x0100000000000002 = INTEL_Y_TILED
		0x20203852 = 'R8  '; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x20203852 = 'R8  '; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x20363152 = 'R16 '; 0x00ffffffffffffff = INVALID
		0x20363152 = 'R16 '; 0x0000000000000000 = LINEAR
		0x20363152 = 'R16 '; 0x0100000000000001 = INTEL_X_TILED
		0x20363152 = 'R16 '; 0x0100000000000002 = INTEL_Y_TILED
		0x20363152 = 'R16 '; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x20363152 = 'R16 '; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x38385247 = 'GR88'; 0x00ffffffffffffff = INVALID
		0x38385247 = 'GR88'; 0x0000000000000000 = LINEAR
		0x38385247 = 'GR88'; 0x0100000000000001 = INTEL_X_TILED
		0x38385247 = 'GR88'; 0x0100000000000002 = INTEL_Y_TILED
		0x38385247 = 'GR88'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x38385247 = 'GR88'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x32335247 = 'GR32'; 0x00ffffffffffffff = INVALID
		0x32335247 = 'GR32'; 0x0000000000000000 = LINEAR
		0x32335247 = 'GR32'; 0x0100000000000001 = INTEL_X_TILED
		0x32335247 = 'GR32'; 0x0100000000000002 = INTEL_Y_TILED
		0x32335247 = 'GR32'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x32335247 = 'GR32'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x39565559 = 'YUV9'; 0x00ffffffffffffff = INVALID
		0x39565559 = 'YUV9'; 0x0000000000000000 = LINEAR
		0x39565559 = 'YUV9'; 0x0100000000000001 = INTEL_X_TILED
		0x39565559 = 'YUV9'; 0x0100000000000002 = INTEL_Y_TILED
		0x31315559 = 'YU11'; 0x00ffffffffffffff = INVALID
		0x31315559 = 'YU11'; 0x0000000000000000 = LINEAR
		0x31315559 = 'YU11'; 0x0100000000000001 = INTEL_X_TILED
		0x31315559 = 'YU11'; 0x0100000000000002 = INTEL_Y_TILED
		0x32315559 = 'YU12'; 0x00ffffffffffffff = INVALID
		0x32315559 = 'YU12'; 0x0000000000000000 = LINEAR
		0x32315559 = 'YU12'; 0x0100000000000001 = INTEL_X_TILED
		0x32315559 = 'YU12'; 0x0100000000000002 = INTEL_Y_TILED
		0x36315559 = 'YU16'; 0x00ffffffffffffff = INVALID
		0x36315559 = 'YU16'; 0x0000000000000000 = LINEAR
		0x36315559 = 'YU16'; 0x0100000000000001 = INTEL_X_TILED
		0x36315559 = 'YU16'; 0x0100000000000002 = INTEL_Y_TILED
		0x34325559 = 'YU24'; 0x00ffffffffffffff = INVALID
		0x34325559 = 'YU24'; 0x0000000000000000 = LINEAR
		0x34325559 = 'YU24'; 0x0100000000000001 = INTEL_X_TILED
		0x34325559 = 'YU24'; 0x0100000000000002 = INTEL_Y_TILED
		0x39555659 = 'YVU9'; 0x00ffffffffffffff = INVALID
		0x39555659 = 'YVU9'; 0x0000000000000000 = LINEAR
		0x39555659 = 'YVU9'; 0x0100000000000001 = INTEL_X_TILED
		0x39555659 = 'YVU9'; 0x0100000000000002 = INTEL_Y_TILED
		0x31315659 = 'YV11'; 0x00ffffffffffffff = INVALID
		0x31315659 = 'YV11'; 0x0000000000000000 = LINEAR
		0x31315659 = 'YV11'; 0x0100000000000001 = INTEL_X_TILED
		0x31315659 = 'YV11'; 0x0100000000000002 = INTEL_Y_TILED
		0x32315659 = 'YV12'; 0x00ffffffffffffff = INVALID
		0x32315659 = 'YV12'; 0x0000000000000000 = LINEAR
		0x32315659 = 'YV12'; 0x0100000000000001 = INTEL_X_TILED
		0x32315659 = 'YV12'; 0x0100000000000002 = INTEL_Y_TILED
		0x36315659 = 'YV16'; 0x00ffffffffffffff = INVALID
		0x36315659 = 'YV16'; 0x0000000000000000 = LINEAR
		0x36315659 = 'YV16'; 0x0100000000000001 = INTEL_X_TILED
		0x36315659 = 'YV16'; 0x0100000000000002 = INTEL_Y_TILED
		0x34325659 = 'YV24'; 0x00ffffffffffffff = INVALID
		0x34325659 = 'YV24'; 0x0000000000000000 = LINEAR
		0x34325659 = 'YV24'; 0x0100000000000001 = INTEL_X_TILED
		0x34325659 = 'YV24'; 0x0100000000000002 = INTEL_Y_TILED
		0x3231564e = 'NV12'; 0x00ffffffffffffff = INVALID
		0x3231564e = 'NV12'; 0x0000000000000000 = LINEAR
		0x3231564e = 'NV12'; 0x0100000000000001 = INTEL_X_TILED
		0x3231564e = 'NV12'; 0x0100000000000002 = INTEL_Y_TILED
		0x3231564e = 'NV12'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x30313050 = 'P010'; 0x00ffffffffffffff = INVALID
		0x30313050 = 'P010'; 0x0000000000000000 = LINEAR
		0x30313050 = 'P010'; 0x0100000000000001 = INTEL_X_TILED
		0x30313050 = 'P010'; 0x0100000000000002 = INTEL_Y_TILED
		0x30313050 = 'P010'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x32313050 = 'P012'; 0x00ffffffffffffff = INVALID
		0x32313050 = 'P012'; 0x0000000000000000 = LINEAR
		0x32313050 = 'P012'; 0x0100000000000001 = INTEL_X_TILED
		0x32313050 = 'P012'; 0x0100000000000002 = INTEL_Y_TILED
		0x32313050 = 'P012'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x36313050 = 'P016'; 0x00ffffffffffffff = INVALID
		0x36313050 = 'P016'; 0x0000000000000000 = LINEAR
		0x36313050 = 'P016'; 0x0100000000000001 = INTEL_X_TILED
		0x36313050 = 'P016'; 0x0100000000000002 = INTEL_Y_TILED
		0x36313050 = 'P016'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x30333050 = 'P030'; 0x00ffffffffffffff = INVALID
		0x30333050 = 'P030'; 0x0000000000000000 = LINEAR
		0x30333050 = 'P030'; 0x0100000000000001 = INTEL_X_TILED
		0x30333050 = 'P030'; 0x0100000000000002 = INTEL_Y_TILED
		0x3631564e = 'NV16'; 0x00ffffffffffffff = INVALID
		0x3631564e = 'NV16'; 0x0000000000000000 = LINEAR
		0x3631564e = 'NV16'; 0x0100000000000001 = INTEL_X_TILED
		0x3631564e = 'NV16'; 0x0100000000000002 = INTEL_Y_TILED
		0x3631564e = 'NV16'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x56555941 = 'AYUV'; 0x00ffffffffffffff = INVALID
		0x56555941 = 'AYUV'; 0x0000000000000000 = LINEAR
		0x56555941 = 'AYUV'; 0x0100000000000001 = INTEL_X_TILED
		0x56555941 = 'AYUV'; 0x0100000000000002 = INTEL_Y_TILED
		0x56555958 = 'XYUV'; 0x00ffffffffffffff = INVALID
		0x56555958 = 'XYUV'; 0x0000000000000000 = LINEAR
		0x56555958 = 'XYUV'; 0x0100000000000001 = INTEL_X_TILED
		0x56555958 = 'XYUV'; 0x0100000000000002 = INTEL_Y_TILED
		0x30313459 = 'Y410'; 0x00ffffffffffffff = INVALID
		0x30313459 = 'Y410'; 0x0000000000000000 = LINEAR
		0x30313459 = 'Y410'; 0x0100000000000001 = INTEL_X_TILED
		0x30313459 = 'Y410'; 0x0100000000000002 = INTEL_Y_TILED
		0x32313459 = 'Y412'; 0x00ffffffffffffff = INVALID
		0x32313459 = 'Y412'; 0x0000000000000000 = LINEAR
		0x32313459 = 'Y412'; 0x0100000000000001 = INTEL_X_TILED
		0x32313459 = 'Y412'; 0x0100000000000002 = INTEL_Y_TILED
		0x36313459 = 'Y416'; 0x00ffffffffffffff = INVALID
		0x36313459 = 'Y416'; 0x0000000000000000 = LINEAR
		0x36313459 = 'Y416'; 0x0100000000000001 = INTEL_X_TILED
		0x36313459 = 'Y416'; 0x0100000000000002 = INTEL_Y_TILED
		0x56595559 = 'YUYV'; 0x00ffffffffffffff = INVALID
		0x56595559 = 'YUYV'; 0x0000000000000000 = LINEAR
		0x56595559 = 'YUYV'; 0x0100000000000001 = INTEL_X_TILED
		0x56595559 = 'YUYV'; 0x0100000000000002 = INTEL_Y_TILED
		0x56595559 = 'YUYV'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x56595559 = 'YUYV'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x56595559 = 'YUYV'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x59565955 = 'UYVY'; 0x00ffffffffffffff = INVALID
		0x59565955 = 'UYVY'; 0x0000000000000000 = LINEAR
		0x59565955 = 'UYVY'; 0x0100000000000001 = INTEL_X_TILED
		0x59565955 = 'UYVY'; 0x0100000000000002 = INTEL_Y_TILED
		0x59565955 = 'UYVY'; 0x0100000000000006 = INTEL_Y_TILED_GEN12_RC_CCS
		0x59565955 = 'UYVY'; 0x0100000000000007 = INTEL_Y_TILED_GEN12_MC_CCS
		0x59565955 = 'UYVY'; 0x0100000000000008 = INTEL_Y_TILED_GEN12_RC_CCS_CC
		0x30313259 = 'Y210'; 0x00ffffffffffffff = INVALID
		0x30313259 = 'Y210'; 0x0000000000000000 = LINEAR
		0x30313259 = 'Y210'; 0x0100000000000001 = INTEL_X_TILED
		0x30313259 = 'Y210'; 0x0100000000000002 = INTEL_Y_TILED
		0x32313259 = 'Y212'; 0x00ffffffffffffff = INVALID
		0x32313259 = 'Y212'; 0x0000000000000000 = LINEAR
		0x32313259 = 'Y212'; 0x0100000000000001 = INTEL_X_TILED
		0x32313259 = 'Y212'; 0x0100000000000002 = INTEL_Y_TILED
		0x36313259 = 'Y216'; 0x00ffffffffffffff = INVALID
		0x36313259 = 'Y216'; 0x0000000000000000 = LINEAR
		0x36313259 = 'Y216'; 0x0100000000000001 = INTEL_X_TILED
		0x36313259 = 'Y216'; 0x0100000000000002 = INTEL_Y_TILED
interface: 'zxdg_output_manager_v1',                     version:  3, name:  4
	xdg_output_v1
		output: 36
		name: 'eDP-1'
		description: 'Thermotrex Corporation 0x1422 0x00007730 (eDP-1)'
		logical_x: 0, logical_y: 0
		logical_width: 1560, logical_height: 1040
interface: 'zwlr_output_manager_v1',                     version:  4, name:  5
interface: 'wl_compositor',                              version:  5, name:  6
interface: 'wl_subcompositor',                           version:  1, name:  7
interface: 'wl_data_device_manager',                     version:  3, name:  8
interface: 'zwp_primary_selection_device_manager_v1',    version:  1, name:  9
interface: 'wl_seat',                                    version:  8, name: 10
	name: seat0
	capabilities: pointer keyboard touch
	keyboard repeat rate: 40
	keyboard repeat delay: 200
interface: 'zwlr_virtual_pointer_manager_v1',            version:  2, name: 11
interface: 'zwp_virtual_keyboard_manager_v1',            version:  1, name: 12
interface: 'zwp_pointer_gestures_v1',                    version:  3, name: 13
interface: 'xdg_wm_base',                                version:  2, name: 14
interface: 'org_kde_kwin_server_decoration_manager',     version:  1, name: 15
interface: 'zxdg_decoration_manager_v1',                 version:  1, name: 16
interface: 'xdg_activation_v1',                          version:  1, name: 17
interface: 'wp_presentation',                            version:  1, name: 18
	presentation clock id: 1 (CLOCK_MONOTONIC)
interface: 'zwlr_export_dmabuf_manager_v1',              version:  1, name: 19
interface: 'zwlr_screencopy_manager_v1',                 version:  3, name: 20
interface: 'zwlr_data_control_manager_v1',               version:  2, name: 21
interface: 'zwlr_gamma_control_manager_v1',              version:  1, name: 22
interface: 'wp_viewporter',                              version:  1, name: 23
interface: 'wp_single_pixel_buffer_manager_v1',          version:  1, name: 24
interface: 'org_kde_kwin_idle',                          version:  1, name: 25
interface: 'ext_idle_notifier_v1',                       version:  1, name: 26
interface: 'zwp_idle_inhibit_manager_v1',                version:  1, name: 27
interface: 'zwp_relative_pointer_manager_v1',            version:  1, name: 28
interface: 'zwp_pointer_constraints_v1',                 version:  1, name: 29
interface: 'zwlr_input_inhibit_manager_v1',              version:  1, name: 30
interface: 'zwlr_foreign_toplevel_manager_v1',           version:  3, name: 31
interface: 'ext_session_lock_manager_v1',                version:  1, name: 32
interface: 'wp_drm_lease_device_v1',                     version:  1, name: 33
	path: /dev/dri/card1
	connector:
		id: 236
		name: eDP-1
		description: Thermotrex Corporation 0x1422 0x00007730 (eDP-1)
interface: 'zwlr_output_power_manager_v1',               version:  1, name: 34
interface: 'zwlr_layer_shell_v1',                        version:  4, name: 35
interface: 'wl_output',                                  version:  4, name: 36
	name: eDP-1
	description: Thermotrex Corporation 0x1422 0x00007730 (eDP-1)
	x: 0, y: 0, scale: 2,
	physical_width: 300 mm, physical_height: 200 mm,
	make: 'Thermotrex Corporation', model: '0x1422',
	subpixel_orientation: unknown, output_transform: normal,
	mode:
		width: 3120 px, height: 2080 px, refresh: 90.000 Hz,
		flags: current
```

**Comment by russelltg** [comment]
Fixed in f08aed59688ca11cd3b4a5ca7840a3df8ff9987d
