### ISSUE TITLE
No usable encoding profile found.

### ISSUE THREAD

**Issue by hholst80** [russelltg/wl-screenrec#41]
Not sure what is going on here. wl-record says vaapi does not support yuv420 but vainfo says it does?

wl-record v0.1.1 compiled via cargo + git.

```
[I] root@fedora ~
# wl-screenrec --verbose
Using output DP-1
Opening libva device from DRM device /dev/dri/renderD128
+----------+
|    in    |default--[3840x2160 0:1 vaapi]--Parsed_crop_0:default
| (buffer) |
+----------+

                                                            +--------------+
Parsed_scale_vaapi_1:default--[3840x2160 0:1 vaapi]--default|     out      |
                                                            | (buffersink) |
                                                            +--------------+

                                          +---------------+
in:default--[3840x2160 0:1 vaapi]--default| Parsed_crop_0 |default--[3840x2160 0:1 vaapi]--Parsed_scale_vaapi_1:default
                                          |    (crop)     |
                                          +---------------+

                                                     +----------------------+
Parsed_crop_0:default--[3840x2160 0:1 vaapi]--default| Parsed_scale_vaapi_1 |default--[3840x2160 0:1 vaapi]--out:default
                                                     |    (scale_vaapi)     |
                                                     +----------------------+


[h264_vaapi @ 0x561374eff900] No usable encoding profile found.
failed to open encoder in low_power mode (Function not implemented), trying non low_power mode. if you have an intel iGPU, set enable_guc=2 in the i915 module to use the fixed function encoder. pass --low-power=off to suppress this warning
[h264_vaapi @ 0x561374effcc0] No usable encoding profile found.
failed to create encoder: Function not implemented
```

```f
[I] root@fedora ~
# wl-screenrec --verbose --no-hw
Using output DP-1
Opening libva device from DRM device /dev/dri/renderD128
[Parsed_scale_vaapi_1 @ 0x55eabd2197c0] Hardware does not support output format yuv420p.
[Parsed_scale_vaapi_1 @ 0x55eabd2197c0] Failed to configure output pad on Parsed_scale_vaapi_1
thread 'main' panicked at src/main.rs:1648:18:
called `Result::unwrap()` on an `Err` value: ffmpeg::Error(22: Invalid argument)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
[I] root@fedora ~ [101]
# vainfo -a
Trying display: wayland
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.18 (libva 2.18.2)
vainfo: Driver version: Mesa Gallium driver 23.1.9 for AMD Radeon VII (vega20, LLVM 16.0.6, DRM 3.54, 6.5.12-200.fc38.x86_64)
vainfo: Supported config attributes per profile/entrypoint pair
VAProfileMPEG2Simple/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420

VAProfileMPEG2Main/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420

VAProfileNone/VAEntrypointVideoProc
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422
                                             VA_RT_FORMAT_YUV444
                                             VA_RT_FORMAT_YUV400
                                             VA_RT_FORMAT_YUV420_10
                                             VA_RT_FORMAT_RGB32
                                             VA_RT_FORMAT_YUV420_10BPP
```

```
[I] root@fedora ~
# ls -alh /dev/dri/*
crw-rw---- 1 root video  226,   0 Nov 26  2023 /dev/dri/card0
crw-rw---- 1 root video  226,   1 Nov 26  2023 /dev/dri/card1
crw-rw-rw- 1 root render 226, 128 Nov 26  2023 /dev/dri/renderD128

/dev/dri/by-path:
total 0
drwxr-xr-x 2 root root 100 Nov 26  2023 ./
drwxr-xr-x 3 root root 120 Nov 26  2023 ../
lrwxrwxrwx 1 root root   8 Nov 26  2023 pci-0000:03:00.0-card -> ../card1
lrwxrwxrwx 1 root root  13 Nov 26  2023 pci-0000:03:00.0-render -> ../renderD128
lrwxrwxrwx 1 root root   8 Nov 26  2023 platform-simple-framebuffer.0-card -> ../card0

[I] root@fedora ~
# lspci |grep 03:00
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 20 [Radeon VII] (rev c1)
03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Vega 20 HDMI Audio [Radeon VII]
```

**Comment by hholst80** [comment]
I find it likely that the reason why it works on my other Fedora box is that it uses an Intel GPU and here on the workstation I have a fancy AMD GPU.

The error message "failed to create encoder: Function not implemented" is perhaps not the best, but besides that I do not think there is much you can help me with here.

https://www.reddit.com/r/linux/comments/xpyggi/comment/iq6nkhn/

**Comment by russelltg** [comment]
Hmm, this is encode and that is decode. Other people have reported this working fine on AMD GPUs, but I don't have one to test.

Unfortunately that error is from ffmpeg.

**Comment by russelltg** [comment]
I have happy users with AMD GPU's (#1, #39, #33). What GPU do you have? Does `ffmpeg -vaapi_device /dev/dri/renderD128 -f lavfi -i rgbtestsrc=duration=5:size=1280x720:rate=30 -vf hwupload,crop=100:100:200:200,scale_vaapi=format=nv12:w=100:h=100 -c:v h264_vaapi testout.mp4` work?

**Comment by hholst80** [comment]
```
[I] root@neo ~
# ffmpeg -vaapi_device /dev/dri/renderD128 -f lavfi -i rgbtestsrc=duration=5:size=1280x720:rate=30 -vf hwupload,crop=100:100:200:200,scale_vaapi=format=nv12:w=100:h=100 -c:v h264_vaapi testout.mp4
ffmpeg version 6.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Unrecognized option 'vaapi_device'.
Error splitting the argument list: Option not found
[I] root@neo ~ [8]
# 
```

```
[I] root@neo ~
# wf-recorder -f test-vaapi.mp4 -c h264_vaapi -d /dev/dri/renderD128
Output file "test-vaapi.mp4" exists. Overwrite? Y/n: y
using VA-API, trying to enable DMA-BUF capture...
enabled DMA-BUF capture, device /dev/dri/renderD128
selected region 0,0 0x0
Using video filter: scale_vaapi=format=nv12:out_range=full
[h264_vaapi @ 0x7f1168002300] No quality level set; using default (20).
[h264_vaapi @ 0x7f1168002300] Driver does not support some wanted packed headers (wanted 0xd, found 0).
[h264_vaapi @ 0x7f1168002300] Driver does not support packed sequence headers, but a global header is requested.
[h264_vaapi @ 0x7f1168002300] No global header will be written: this may result in a stream which is not usable for some purposes (e.g. not muxable to some containers).
Output #0, mp4, to 'test-vaapi.mp4':
  Stream #0:0: Video: h264 (High), vaapi(pc), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31
^C⏎                                                                                                    [I] root@neo ~
# wl-screenrec --dri-device /dev/dri/renderD128
Using output DP-1
Opening libva device from DRM device /dev/dri/renderD128
[h264_vaapi @ 0x564efc28fac0] No usable encoding entrypoint found for profile VAProfileH264High (7).
failed to open encoder in low_power mode (Function not implemented), trying non low_power mode. if you have an intel iGPU, set enable_guc=2 in the i915 module to use the fixed function encoder. pass --low-power=off to suppress this warning
[h264_vaapi @ 0x564efc28fac0] Driver does not support some wanted packed headers (wanted 0xd, found 0).
[h264_vaapi @ 0x564efc28fac0] Driver does not support packed sequence headers, but a global header is requested.
[h264_vaapi @ 0x564efc28fac0] No global header will be written: this may result in a stream which is not usable for some purposes (e.g. not muxable to some containers).
[h264_vaapi @ 0x564efc28fac0] Failed to upload encode parameters: 2 (resource allocation failed).
[h264_vaapi @ 0x564efc28fac0] Encode failed: -5.
thread 'main' panicked at src/main.rs:1426:51:
called `Result::unwrap()` on an `Err` value: ffmpeg::Error(5: Input/output error)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[I] root@neo ~ [101]
# vainfo
Trying display: wayland
vainfo: VA-API version: 1.20 (libva 2.20.0)
vainfo: Driver version: Mesa Gallium driver 23.2.1-arch1.2 for AMD Radeon VII (vega20, LLVM 16.0.6, DRM 3.49, 6.1.64-1-lts)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
[I] root@neo ~
# 
```

**Comment by Ristovski** [comment]
Just to be safe, can you show the output of `ffmpeg -hwaccels`?
Should look something like this:
```
Hardware acceleration methods:
vdpau
vaapi
drm
vulkan
```

(not sure if this has been merged into upstream ffmpeg, but the "Cannot allocate memory" message might be bogus as per https://patchwork.ffmpeg.org/project/ffmpeg/patch/484c6644-dfcd-1ad9-95fe-4bf2a06b30e7@jkqxz.net/)

**Comment by hholst80** [comment]
It only shows vdpau ... ?

**Comment by Ristovski** [comment]
> It only shows vdpau ... ?

@hholst80 That is weird, its as if your ffmpeg build does not have vaapi enabled for some reason. `vdpau` is only for hw accelerated _decoding_.

Can you check the output of `ffmpeg -buildconf | grep -Ei "vdpau|vaapi"`?

For me it shows both `--enable-vaapi` and `--enable-vdpau` (which correlates to my `ffmpeg -hwaccels` output)

**Comment by russelltg** [comment]
Is wl-screenrec using the right ffmpeg? `lld $(which wl-screenrec)`

**Comment by russelltg** [comment]
Could wl-screenrec be using the wrong ffmpeg? `ldd $(which wl-screenrec)`

**Comment by russelltg** [comment]
I don't think so. You're welcome to test this patch against latest `main`:

```patch
diff --git a/src/main.rs b/src/main.rs
index fd62896..a2790ad 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1423,7 +1423,9 @@ impl EncState {
             .is_ok()
         {
             // encoder has same time base as the filter, so don't do any time scaling
-            self.enc_video.send_frame(&yuv_frame).unwrap();
+            if let Err(e) = self.enc_video.send_frame(&yuv_frame) {
+                eprintln!("Failed to encode: {e}")
+            }
         }
 
         let mut encoded = Packet::empty();
```

I'll probably push this patch anyways as it's less nasty than a panic, and I suppose maybe sometimes that error isn't fatal. It's hard to say.

I would be interested in full `strace` outputs from those two commands to see exactly what is failing.

**Comment by hholst80** [comment]
on git sha 6110ba66495c65b913cf50afb595eab7b992cb34 I get this.  

Seems to be the same error message as I got on the "new machine" (called "goblin") in #64 

This is on the same hardware as before on my "neo" machine.

```
[I] root@neo ~
# wl-screenrec --low-power=off --encode-resolution 1920x1080 --audio
Using output DP-1
Opening libva device from DRM device /dev/dri/renderD128
[Parsed_crop_0 @ 0x57ec399cf580] Invalid too big or non positive size for width '3840' or height '2160'
[Parsed_crop_0 @ 0x57ec399cf580] Failed to configure input pad on Parsed_crop_0
thread 'main' panicked at src/main.rs:1706:18:
called `Result::unwrap()` on an `Err` value: ffmpeg::Error(22: Invalid argument)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[I] root@neo ~ [101]
#
```

```
[I] root@neo ~
# vainfo
Trying display: wayland
vainfo: VA-API version: 1.20 (libva 2.20.1)
vainfo: Driver version: Mesa Gallium driver 24.0.1-arch1.1 for AMD Radeon VII (radeonsi, vega20, LLVM 16.0.6, DRM 3.57, 6.7.5-zen1-1-zen)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
[I] root@neo ~
#
```

[vvv.txt](https://github.com/russelltg/wl-screenrec/files/14464044/vvv.txt)

**Comment by hholst80** [comment]
Aha!
This might be related to non-integer scaling (I am exploring the best way to do HiDPI in a portable way between my many machines.).

If I use an integer scaling, like 2 instead of 2.4 like I am using now on both neo and goblin, I get this more familiar error message:

```
[I] root@neo ~/Apps/wl-screenrec (main)
# wl-screenrec --low-power=off --encode-resolution 1920x1080 --audio
Opening libva device from DRM device /dev/dri/renderD128
[h264_vaapi @ 0x588bbf9c5cc0] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[h264_vaapi @ 0x588bbf9c5cc0] Failed to upload encode parameters: 2 (resource allocation failed).
[h264_vaapi @ 0x588bbf9c5cc0] Encode failed: -5.
thread 'main' panicked at src/main.rs:1505:51:
called `Result::unwrap()` on an `Err` value: ffmpeg::Error(5: Input/output error)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[I] root@neo ~/Apps/wl-screenrec (main) [101]
#
```

**Comment by russelltg** [comment]
Reported upstream at https://github.com/hyprwm/Hyprland/issues/4991

**Comment by russelltg** [comment]
It's possible I should handle this better by clamping the size to the dmabuf size...but it's truly unexpected that the dmabuf size is too small...

**Comment by russelltg** [comment]
Does 


```bash
ffmpeg -vaapi_device /dev/dri/renderD128 -hwaccel vaapi -f lavfi -i testsrc=duration=10:size=1280x720 -filter_complex 'hwupload,scale_vaapi=format=nv12' -c:v h264_vaapi -loglevel 80 test.mp4
```

work and create a valid video?

**Comment by SArpnt** [comment]
i've recorded videos with this program before, but i started having this exact issue some time ago and i'm not sure what caused it.

```
sarpnt@mime-cube 
---------------- 
OS: Arch Linux x86_64 
Kernel: 6.9.2-zen1-1-zen 
Uptime: 1 hour, 10 mins 
Packages: 1298 (pacman) 
Shell: fish 3.7.1 
Resolution: 1920x1080 
WM: sway 
Theme: oomox-darker-than-fusion [GTK2/3] 
Icons: breeze-dark [GTK2/3] 
Terminal: foot 
CPU: Intel i5-4690K (4) @ 3.900GHz 
GPU: Intel HD Graphics 
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
Memory: 3708MiB / 11828MiB 
```
```
sarpnt@mime-cube ~> wl-screenrec
Opening libva device from DRM device /dev/dri/renderD129
[h264_vaapi @ 0x5604f2686d40] No usable encoding entrypoint found for profile VAProfileH264High (7).
failed to open encoder in low_power mode (Function not implemented), trying non low_power mode. if you have an intel iGPU, set enable_guc=2 in the i915 module to use the fixed function encoder. pass --low-power=off to suppress this warning
[h264_vaapi @ 0x5604f2686d40] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[h264_vaapi @ 0x5604f2686d40] Failed to upload encode parameters: 2 (resource allocation failed).
[h264_vaapi @ 0x5604f2686d40] Encode failed: -5.
thread 'main' panicked at src/main.rs:1564:51:
called `Result::unwrap()` on an `Err` value: ffmpeg::Error(5: Input/output error)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
sarpnt@mime-cube ~ [101]> wl-screenrec --no-hw
Opening libva device from DRM device /dev/dri/renderD129
[Parsed_scale_vaapi_1 @ 0x634217b0d580] Hardware does not support output format yuv420p.
[Parsed_scale_vaapi_1 @ 0x634217b0d580] Failed to configure output pad on Parsed_scale_vaapi_1
thread 'main' panicked at src/main.rs:1782:18:
called `Result::unwrap()` on an `Err` value: ffmpeg::Error(22: Invalid argument)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

vainfo shows the amd card should work and ffmpeg with vaapi encoding works fine

**Comment by choucavalier** [comment]
been having this issue as well


an excerpt from the debug logs:

```

                                                            +--------------+
Parsed_scale_vaapi_1:default--[3840x2160 0:1 vaapi]--default|     out      |
                                                            | (buffersink) |
                                                            +--------------+

                                          +---------------+
in:default--[3840x2160 0:1 vaapi]--default| Parsed_crop_0 |default--[3840x2160 0:1 vaapi]--Parsed_scale_vaapi_1:default
                                          |    (crop)     |
                                          +---------------+

                                                     +----------------------+
Parsed_crop_0:default--[3840x2160 0:1 vaapi]--default| Parsed_scale_vaapi_1 |default--[3840x2160 0:1 vaapi]--out:default
                                                     |    (scale_vaapi)     |
                                                     +----------------------+


[h264_vaapi @ 0x631c5c96d240] Input surface format is nv12.
[h264_vaapi @ 0x631c5c96d240] Using VAAPI profile VAProfileH264High (7).
[h264_vaapi @ 0x631c5c96d240] No usable encoding entrypoint found for profile VAProfileH264High (7).
failed to open encoder in low_power mode (Function not implemented), trying non low_power mode. if you have an intel iGPU, set enable_guc=2 in the i915 module to use the fixed function encoder. pass --low-power=off to suppress this warning
[h264_vaapi @ 0x631c5c96d240] Input surface format is nv12.
[h264_vaapi @ 0x631c5c96d240] Using VAAPI profile VAProfileH264High (7).
[h264_vaapi @ 0x631c5c96d240] Using VAAPI entrypoint VAEntrypointEncSlice (6).
[h264_vaapi @ 0x631c5c96d240] Using VAAPI render target format YUV420 (0x1).
[h264_vaapi @ 0x631c5c96d240] Driver supports RC modes CQP, CBR, VBR, QVBR.
[h264_vaapi @ 0x631c5c96d240] Driver does not support AVBR RC mode.
[h264_vaapi @ 0x631c5c96d240] RC mode: VBR.
[h264_vaapi @ 0x631c5c96d240] Block Level bitrate control: OFF.
[h264_vaapi @ 0x631c5c96d240] RC target: 50% of 80000000 bps over 500 ms.
[h264_vaapi @ 0x631c5c96d240] RC buffer: 40000000 bits, initial fullness 30000000 bits.
[h264_vaapi @ 0x631c5c96d240] RC framerate: 60/1 (60.00 fps).
[h264_vaapi @ 0x631c5c96d240] Driver does not report any additional prediction constraints.
[h264_vaapi @ 0x631c5c96d240] Using intra, P- and B-frames (supported references: 1 / 1).
[h264_vaapi @ 0x631c5c96d240] All wanted packed headers available (wanted 0xd, found 0x1f).
[h264_vaapi @ 0x631c5c96d240] Using nv12 as format of reconstructed frames.
[AVHWFramesContext @ 0x631c5cae2580] Created surface 0xf.
[AVHWFramesContext @ 0x631c5cae2580] Direct mapping possible.
Output #0, mp4, to 'screenrecord.mp4':
  Metadata:
    encoder         : Lavf61.7.100
  Stream #0:0, 0, 1/90000: Video: h264 (High), 1 reference frame (avc1 / 0x31637661), vaapi, 3840x2160, 0/1, q=2-31, 40000 kb/s, 90k tbn
10:37:17 [0m[36m[DEBUG] [0m(1) wayland_backend::rs::client_impl: Sending zwp_linux_dmabuf_v1@3.create_params (zwp_linux_buffer_params_v1@12)
10:37:17 [0m[36m[DEBUG] [0m(1) wayland_backend::rs::client_impl: Sending zwp_linux_buffer_params_v1@12.add (8, 0, 0, 15360, 0, 0)
10:37:17 [0m[36m[DEBUG] [0m(1) wayland_backend::rs::client_impl: Sending zwp_linux_buffer_params_v1@12.create_immed (wl_buffer@13, 3840, 2160, 875713112, 0)
10:37:17 [0m[36m[DEBUG] [0m(1) wayland_backend::rs::client_impl: Sending zwlr_screencopy_frame_v1@11.copy_with_damage (wl_buffer@13)
10:37:17 [0m[36m[DEBUG] [0m(1) wl_screenrec::cap_wlr_screencopy: zwlr-screencopy-frame event: ObjectId(zwlr_screencopy_frame_v1@11, 11) BufferDone
10:37:17 [0m[36m[DEBUG] [0m(1) wayland_backend::rs::client_impl: Dispatching zwlr_screencopy_frame_v1@11.3 (0)
10:37:17 [0m[36m[DEBUG] [0m(1) wayland_backend::rs::client_impl: Dispatching zwlr_screencopy_frame_v1@11.3 (0, 0, 3840, 2160)
10:37:17 [0m[36m[DEBUG] [0m(1) wayland_backend::rs::client_impl: Dispatching zwlr_screencopy_frame_v1@11.3 (0, 160663, 808456522)
10:37:17 [0m[36m[DEBUG] [0m(1) wayland_backend::rs::client_impl: Dispatching wl_buffer@13.4 ()
10:37:17 [0m[36m[DEBUG] [0m(1) wl_screenrec::cap_wlr_screencopy: zwlr-screencopy-frame event: ObjectId(zwlr_screencopy_frame_v1@11, 11) Flags { flags: Value(Flags(0x0)) }
10:37:17 [0m[36m[DEBUG] [0m(1) wl_screenrec::cap_wlr_screencopy: zwlr-screencopy-frame event: ObjectId(zwlr_screencopy_frame_v1@11, 11) Damage { x: 0, y: 0, width: 3840, height: 2160 }
10:37:17 [0m[36m[DEBUG] [0m(1) wl_screenrec::cap_wlr_screencopy: zwlr-screencopy-frame event: ObjectId(zwlr_screencopy_frame_v1@11, 11) Ready { tv_sec_hi: 0, tv_sec_lo: 160663, tv_nsec: 808456522 }
10:37:17 [0m[36m[DEBUG] [0m(1) wayland_backend::rs::client_impl: Sending zwlr_screencopy_frame_v1@11.destroy ()
10:37:17 [0m[36m[DEBUG] [0m(1) wayland_backend::rs::client_impl: Sending wl_buffer@13.destroy ()
[in @ 0x631c5cad3d80] video frame properties congruent with link at pts_time: 0
```

output of vainfo

```
Trying display: wayland
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Mesa Gallium driver 25.0.5-arch1.1 for AMD Radeon Graphics (radeonsi, rembrandt, LLVM 19.1.7, DRM 3.61, 6.14.4-arch1-2)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```
